CREATE TABLE "Player" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "nationality" TEXT NOT NULL,
  "ranking" INTEGER
);

CREATE TABLE "Tournament" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "location" TEXT NOT NULL,
  "startDate" DATETIME NOT NULL,
  "endDate" DATETIME NOT NULL
);

CREATE TABLE "Match" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "tournamentId" INTEGER NOT NULL,
  "player1Id" INTEGER NOT NULL,
  "player2Id" INTEGER NOT NULL,
  "winnerId" INTEGER,
  "round" INTEGER NOT NULL,
  "score" TEXT,
  FOREIGN KEY ("tournamentId") REFERENCES "Tournament"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("player1Id") REFERENCES "Player"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("player2Id") REFERENCES "Player"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY ("winnerId") REFERENCES "Player"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
